version: '3.8'

services:
  sora-video-studio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: sora-video-studio
    networks:
      - sora-network

networks:
  sora-network:
    driver: bridge
